
-- alter table 테이블 명 add 컬럼명 : 컬럼 추가
-- alter table 테이블 명 modify 컬럼명 : 컬럼 수정
-- alter table 테이블 명 drop 컬럼명 : 컬럼 삭제

CREATE TABLE TEST_TABLE ( NUM NUMBER ); -- 합성어는 밑줄(_)로 구분

DESC TEST_TABLE;

ALTER TABLE TEST_TABLE ADD ( NAME VARCHAR2(20) ); -- 컬럼 추가
ALTER TABLE TEST_TABLE MODIFY ( NAME NUMBER ); -- 컬럼 수정
ALTER TABLE TEST_TABLE DROP COLUMN NAME; -- 컬럼 삭제
ALTER TABLE TEST_TABLE RENAME COLUMN NUM TO NUM_BB; -- 컬럼명 수정

DESC TEST_TABLE;

DROP TABLE TEST_TABLE;

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE KOR > 90;
SELECT * FROM STUDENT WHERE KOR != 100;
SELECT * FROM STUDENT WHERE ENG > 90;

SELECT MATH/2 FROM STUDENT WHERE ID='1001';
SELECT MATH+100 FROM STUDENT WHERE ID='1001';
SELECT MATH-100 FROM STUDENT WHERE ID='1001';

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE KOR >= 90 AND MATH=100;
SELECT * FROM STUDENT WHERE KOR >= 90 OR MATH=100;
SELECT * FROM STUDENT WHERE NOT KOR=100;

SELECT * FROM STUDENT WHERE KOR >= 90 AND KOR <=100;
SELECT * FROM STUDENT WHERE KOR BETWEEN 90 AND 100;

CREATE TABLE TEST_NUMBER(
    NUM_PS NUMBER(5,2), -- (전체 자리수, 소수점 자리수)
    NUM_P NUMBER(3), -- 정수 자리수
    NUM NUMBER -- 정수 실수 가변
);

SELECT * FROM TEST_NUMBER;

INSERT INTO TEST_NUMBER VALUES (1.12345, 1.12345, 1.12345);

SELECT * FROM test_number;

INSERT INTO TEST_NUMBER VALUES (1234.56, 1.12345, 1.12345); -- 총 5자리 => 자릿수 벗어나므로 오류발생
INSERT INTO TEST_NUMBER VALUES (1.12345, 12345, 1.12345); -- 총 3자리 => 자릿수 벗어나므로 오류발생



CREATE TABLE TEST_DATE( MY_DATE DATE);
INSERT INTO TEST_DATE VALUES ( SYSDATE ); -- 현재 시스템 날짜
INSERT INTO TEST_DATE VALUES ( '2023/07/03' );
SELECT * FROM TEST_DATE;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
SELECT * FROM TEST_DATE;
INSERT INTO TEST_DATE VALUES ( '2023/07/03 12:12:12' );

SELECT * FROM TEST_DATE WHERE MY_DATE < '2023/07/03 12:12:12'; -- 날짜도 비교가 가능하다
SELECT * FROM TEST_DATE WHERE MY_DATE < '2023/07/04';



CREATE TABLE TEST_CHAR(
    CH CHAR(5), -- 고정 크기
    VCH VARCHAR2(5) -- 가변 크기
);

INSERT INTO TEST_CHAR VALUES('1', '1');    -- 5, 1
INSERT INTO TEST_CHAR VALUES('1', '1234'); -- 5, 4
SELECT LENGTHB(CH), LENGTHB(VCH) FROM TEST_CHAR;



SELECT * FROM EMPLOYEE WHERE NAME LIKE '김%'; -- 김으로 시작하는 모든 값
SELECT * FROM EMPLOYEE WHERE NAME LIKE '%똥'; -- 똥으로 끝나는 모든 값
SELECT * FROM EMPLOYEE WHERE NAME LIKE '%이%'; -- '이'가 들어가는 모든 값

SELECT * FROM EMPLOYEE ORDER BY JOIN_COMPANY DESC; -- 내림차순
SELECT * FROM EMPLOYEE ORDER BY JOIN_COMPANY ASC; -- 오름차순

-- JOB은 오름차순으로 나온 결과 중 SALARY는 내림차순으로
SELECT * FROM EMPLOYEE ORDER BY JOB ASC, SALARY DESC;

